name: Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: 22
          command: cd ${{ secrets.PWD }} && git pull && composer i && npm i && npm run build